global:
  scrape_interval: 5s     # By default, scrape targets every 15 seconds.

scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets: ["localhost:9090"]
  - job_name: user-service
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ["user-service:8080"]
  - job_name: engagement-service
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ["engagement-service:8080"]
global:
  scrape_interval: 5s     # By default, scrape targets every 15 seconds.

